### ISSUE TITLE
On iOS, when rotating device, gradient stays the same

### ISSUE THREAD

**Issue by gunpuz** [DevsDNA/GradientBoxView#3] opened 2018-09-26 09:10 UTC
On iOS, when rotating the device Red field is visible.
On Android it is fine.

What i am trying to achieve is, that full background is gradient
My code:
```
<RelativeLayout>
        <devsdna:GradientBoxView 
            TopColor="Green" 
            BottomColor="Teal"
            BackgroundColor="Red"
            
            RelativeLayout.XConstraint= "{ConstraintExpression Type=RelativeToParent,  Property=X, Constant=0}"
            RelativeLayout.YConstraint= "{ConstraintExpression Type=RelativeToParent, Property=Y, Constant=0}"
            RelativeLayout.HeightConstraint = "{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1}"
            RelativeLayout.WidthConstraint = "{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1}"   
        />
```

**Comment by MarcosCobena** [comment] 2018-11-07 07:17
Hi @gunpuz,

Sorry if I'm late into this.

Would it be possible you send us a project we could reproduce? Currently it looks like an issue when doing the layout calcs at rotating but who knows :-)

Thanks in advance.

**Comment by MarcosCobena** [comment] 2018-11-07 07:17
Also, does the same issue happen when moving from a RelativeLayout to an AbsoluteLayout one?

**Comment by MarcosCobena** [comment] 2018-12-20 07:21
Let me please close this issue for now, feel free to reopen it if may be needed again.

**Closed as completed by MarcosCobena** 2018-12-20 07:21 UTC
